set(ROOT "/Users/goat/draft")
set(ARCHIVE "/Users/goat/draft/dist/legacy-builds")
file(MAKE_DIRECTORY "/Users/goat/draft/dist")
file(MAKE_DIRECTORY "/Users/goat/draft/dist/legacy-builds")
foreach(name build build-win app app_gui)
  set(src "/")
  if(EXISTS )
    file(RENAME  "/")
  endif()
endforeach()
